version: "3.1"

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: rexray
    external: true
