# Stack de servicios para cluster de Docker Swarm

# https://docs.docker.com/engine/swarm/stack-deploy/
# https://docs.docker.com/compose/compose-file/

version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
  spring-boot-app:
    ports:
      - 8080:8080
    deploy:
      replicas: 2
    volumes:
      - data:/data
    secrets:
      - message
networks:
  nginx:
volumes:
  data:
    driver: rexray
    external: true
secrets:
  message:
    file: message
