version: '3'

services:
  db:
    image: postgres
    #restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - db.env

  app:  
    image: nextcloud:fpm
    #restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    image: nginx
    #restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
      - LETSENCRYPT_EMAIL=localhost@localhost
    depends_on:
      - app
    networks:
      - default
      - proxy-tier

  proxy:
    image: jwilder/nginx-proxy:alpine
    #restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    #restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
