version: '3.3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://localhost'
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/localhost.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/localhost.key'
    ports:
      - '22:22'
      - '80:80'
      - '443:443'
    volumes:
      - '/run/media/picodotdev/BMOVE ROJO/docker-volumes/gitlab/config:/etc/gitlab'
      - '/run/media/picodotdev/BMOVE ROJO/docker-volumes/gitlab/logs:/var/log/gitlab'
      - '/run/media/picodotdev/BMOVE ROJO/docker-volumes/gitlab/data:/var/opt/gitlab'
      - '/run/media/picodotdev/BMOVE ROJO/docker-volumes/gitlab/ssl:/etc/gitlab/ssl'

