server:
  port: ${port:8085}

zuul:
  routes:
    service: '/service/**'

service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
