server:
  port: ${port:8085}

zuul:
  routes:
    service: '/service/**'

hystrix:
  command:
    service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    circuitBreaker:
      requestVolumeThreshold: 4
      errorThresholdPercentage: 50

service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
