server:
  port: ${port:8080}

spring:
  application:
    name: service
  profiles:
    active: cloud
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://ds1.127.0.0.1.xip.io:8761/eureka/,http://ds2.127.0.0.1.xip.io:8762/eureka/,http://ds3.127.0.0.1.xip.io:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

config:
  key: value
